
start_week: 1
start_date: 2019-08-04 
num_weeks: 6
extra_exam_week: false

instructor_url: https://ucsb-cs8.github.io/instructor

cal_dates: >
  [
  {"label":"Session B starts", "date":"2019-06-24" },
  {"label":"Univ Holiday", "date":"2019-09-02" , "holiday":true},
  {"label":"Drop deadline (full refund)","date":"2019-08-09" },
  {"label":"Drop deadline (no W grade)","date":"2019-08-20" },
  {"label":"Session B Ends", "date":"2019-09-14" },  
  ]

